name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run CI message
        run: echo "CI Running"

      - name: Create artifact file
        run: |
          mkdir output
          echo "This is a CI artifact" > output/artifact.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifact
          path: output/artifact.txt
